# Generated by Django 6.0.4 on 2026-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('confirmed', 'Order Confirmed'), ('delivering', 'Order Delivering')], default='received', max_length=20),
        ),
    ]
