# Generated by Django 6.0.4 on 2026-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('confirmed', 'Order Confirmed'), ('delivering', 'Order Delivering'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled')], default='received', max_length=20),
        ),
    ]
