from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:pk>/', views.product_detail, name='detail'),
    path('add/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('remove/<str:key>/', views.remove_from_cart, name='remove_from_cart'),
    path('update/<str:key>/', views.update_cart, name='update_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/<int:pk>/', views.order_confirmation, name='order_confirmation'),
    path('orders/', views.order_history, name='order_history'),
    path('orders/<int:pk>/', views.order_detail, name='order_detail'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/', views.change_password, name='change_password'),
    path('change_password/', views.change_password, name='change_password_alt'),
    path('contact/', views.contact, name='contact'),
    path('contact-messages/', views.contact_messages, name='contact_messages'),
    path('manage-accounts/', views.manage_accounts, name='manage_accounts'),
    path('manage-accounts/create/', views.create_account, name='create_account'),
    path('manage-accounts/delete/<int:pk>/', views.delete_account, name='delete_account'),
    path('manage-accounts/toggle-admin/<int:pk>/', views.toggle_admin, name='toggle_admin'),
    path('manage-accounts/change-password/<int:pk>/', views.admin_change_password, name='admin_change_password'),
    path('manage-accounts/mark-read/<int:pk>/', views.mark_contact_read, name='mark_contact_read'),
    path('management/', views.management, name='management'),
    path('management/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('management/edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('add-product/', views.add_product, name='add_product'),
    path('management/orders/<int:pk>/', views.admin_order_detail, name='admin_order_detail'),
    path('management/orders/<int:pk>/status/', views.update_order_status, name='update_order_status'),
    path('management/orders/<int:pk>/complete/', views.complete_order, name='complete_order'),
    path('management/orders/<int:pk>/cancel/', views.cancel_order, name='cancel_order'),
    path('management/orders/<int:pk>/delete-permanent/', views.delete_order_permanently, name='delete_order_permanent'),
]